AN-657 | Add deployment phase 2 and 3 networks
api3dao/airnode pull request #1007
Opened 2022-04-12 06:08 UTC by dcroote

2022-04-12 06:32 UTC, bbenligiray commented
I'll let @bdrhn9 review this

2022-04-12 08:27 UTC, bdrhn9 requested changes

2022-04-13 05:53 UTC, dcroote commented on packages/airnode-node/src/evm/networks.ts
> +  | 4002
Good catch, thanks.

2022-04-13 06:30 UTC, bdrhn9 approved these changes

2022-04-13 06:33 UTC, merged