Retry api call
api3dao/airnode pull request #1691
Opened 2023-03-22 15:04 UTC by Ashar2shahid

closes #1658

2023-03-22 15:29 UTC, Ashar2shahid commented
@bdrhn9 @amarthadan thoughts on which is better ?

2023-03-23 07:44 UTC, amarthadan commented
I see. Well, if we want to avoid Axios blocking file descriptors we should go with option 2. I don't think having those few extra lines is a big deal.

2023-03-29 10:36 UTC, Siegrift requested changes
The extra complexity with `TIMEOUT/3` and `TIMEOUT*2/3` is not worth it. I think it's better to define two constants FIRST_API_CALL_TIMEOUT and SECOND_API_CALL_TIMEOUT.

2023-03-29 10:36 UTC, Siegrift commented on packages/airnode-node/src/api/index.ts
> +  // timeout passed to adapter will cause axios socket to hang until the timeout is reached
Missing line stop.
```suggestion
  // . Timeout passed to adapter will cause axios socket to hang until the timeout is reached
```

2023-03-29 10:36 UTC, Siegrift commented on packages/airnode-node/src/api/index.ts
>    if (!goRes.success) {
nit: prefer early return and avoid nesting.

2023-03-29 13:37 UTC, Siegrift approved these changes
👍 LGTM after the naming improvements.

2023-03-29 13:37 UTC, Siegrift commented on packages/airnode-node/src/api/index.ts
> +  const firstTimeout = FIRST_API_CALL_TIMEOUT;
Just inline the constants. No need to redefine these variables.

2023-03-29 13:37 UTC, Siegrift commented on packages/airnode-node/src/api/index.ts
> +  // timeout passed to adapter will cause axios socket to hang until the timeout is reached
```suggestion
  // Timeout passed to adapter will cause axios socket to hang until the timeout is reached
```

2023-03-29 13:37 UTC, Siegrift commented on packages/airnode-node/src/api/index.ts
> +  const goRes = await go(() => adapter.buildAndExecuteRequest(options, { timeout: firstTimeout }), {
```suggestion
  const goAttempt1 = await go(() => adapter.buildAndExecuteRequest(options, { timeout: firstTimeout }), {
```

2023-03-29 13:37 UTC, Siegrift commented on packages/airnode-node/src/api/index.ts
> +  const goRes2 = await go(() => adapter.buildAndExecuteRequest(options, { timeout: secondTimeout }), {
```suggestion
  const goAttempt2 = await go(() => adapter.buildAndExecuteRequest(options, { timeout: secondTimeout }), {
```

2023-03-30 21:57 UTC, merged